backend:
  name: git-gateway
  branch: develop

# for using local backend run "npm run local" and enter in /admin
local_backend: true

media_folder: assets/media
public_folder: assets/public_media

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    filter: {field: "categories", value: "blog"}
    sort: "date:desc"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Post Category", name: "categories", widget: "hidden", default: "no-category"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
